_core:
  default_config_hash: l58O_yEXSo-SeJi19LXdzTU1tNJG3lmnIhCitRkM1tk
langcode: en
uuid: 86e97fb4-526b-4cc1-8bb9-dc81cb9a5313
name: 'Drupal Devcontainer Demo'
mail: admin@example.com
slogan: 'Developed by Ryan Robinson'
page:
  403: ''
  404: ''
  front: /user/login
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
